-- =========================================================
-- GREENCITY SUPABASE DATABASE
-- Run this whole file once in a NEW GreenCity Supabase project.
-- It is designed to work with the supplied booking/price pages.
-- =========================================================

create extension if not exists pgcrypto;

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  appointment_number text unique not null,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  service_type text not null,
  item_details text not null,
  area text not null,
  address text not null,
  preferred_date date not null,
  preferred_time time not null,
  notes text,
  status text not null default 'pending'
    check (status in ('pending','confirmed','cancelled','completed')),
  service_price numeric(10,2),
  tip numeric(10,2) default 0,
  total numeric(10,2),
  created_at timestamptz not null default now()
);

create table if not exists public.prices (
  id bigint generated by default as identity primary key,
  item_name text not null,
  search_name text not null,
  service_type text not null,
  price numeric(10,2) not null,
  active boolean not null default true
);

create table if not exists public.price_access_codes (
  id bigint generated by default as identity primary key,
  code_hash text not null,
  active boolean not null default true,
  expires_at timestamptz
);

alter table public.bookings enable row level security;
alter table public.prices enable row level security;
alter table public.price_access_codes enable row level security;

drop policy if exists "public can create bookings" on public.bookings;
create policy "public can create bookings"
on public.bookings
for insert to anon, authenticated
with check (true);

-- Appointment lookup is deliberately done through an RPC below.
-- No broad public SELECT policy is needed.

create or replace function public.verify_price_code(p_code text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  return exists (
    select 1
    from public.price_access_codes
    where active
      and (expires_at is null or expires_at > now())
      and crypt(p_code, code_hash) = code_hash
  );
end;
$$;

create or replace function public.get_vehicle_price(
  p_code text,
  p_search text
)
returns table(item_name text, price numeric)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.verify_price_code(p_code) then
    return;
  end if;

  return query
  select p.item_name, p.price
  from public.prices p
  where p.active
    and (
      lower(p.item_name) like '%' || lower(p_search) || '%'
      or lower(p.search_name) like '%' || lower(p_search) || '%'
    )
  order by p.item_name;
end;
$$;

create or replace function public.get_appointment(p_number text)
returns table(
  appointment_number text,
  customer_name text,
  service_type text,
  item_details text,
  area text,
  preferred_date date,
  preferred_time time,
  status text
)
language sql
security definer
set search_path = public
as $$
  select
    b.appointment_number,
    b.customer_name,
    b.service_type,
    b.item_details,
    b.area,
    b.preferred_date,
    b.preferred_time,
    b.status
  from public.bookings b
  where upper(b.appointment_number) = upper(p_number)
  limit 1;
$$;

grant execute on function public.verify_price_code(text) to anon, authenticated;
grant execute on function public.get_vehicle_price(text,text) to anon, authenticated;
grant execute on function public.get_appointment(text) to anon, authenticated;

-- Example prices. Replace these with your final GreenCity price list.
insert into public.prices (item_name, search_name, service_type, price)
select * from (values
  ('Small Car Exterior', 'small car', 'Mobile Car Wash', 250.00),
  ('Sedan Exterior', 'sedan', 'Mobile Car Wash', 300.00),
  ('SUV Exterior', 'suv', 'Mobile Car Wash', 350.00),
  ('Large SUV / Bakkie Exterior', 'bakkie', 'Mobile Car Wash', 400.00),
  ('120L Wheelie Bin', '120l', 'Wheelie Bin Cleaning', 80.00),
  ('240L Wheelie Bin', '240l', 'Wheelie Bin Cleaning', 100.00),
  ('360L Wheelie Bin', '360l', 'Wheelie Bin Cleaning', 130.00)
) as v(item_name, search_name, service_type, price)
where not exists (select 1 from public.prices);

-- Temporary example customer access code: GC2026
insert into public.price_access_codes (code_hash)
select crypt('GC2026', gen_salt('bf'))
where not exists (select 1 from public.price_access_codes);
